"""Generate GitHub demo media from the synthetic DICOM privacy benchmark."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT / "outputs" / "demo-media"
ASSETS = ROOT / "docs" / "assets"
WIDTH = 1280
HEIGHT = 720


def _load_font(size: int, *, mono: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = (
        [
            Path("C:/Windows/Fonts/consola.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"),
        ]
        if mono
        else [
            Path("C:/Windows/Fonts/segoeui.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        ]
    )
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size=size)
    return ImageFont.load_default()


FONT_TITLE = _load_font(42)
FONT_H2 = _load_font(28)
FONT_SMALL = _load_font(18)
FONT_MONO = _load_font(20, mono=True)


def _run_demo(workspace: Path) -> str:
    if workspace.exists():
        shutil.rmtree(workspace)
    cmd = [
        sys.executable,
        "-m",
        "dicom_privacy_auditor.demo",
        str(workspace),
        "--cases-per-stratum",
        "1",
        "--clean-controls",
        "2",
        "--seed",
        "20260628",
        "--overwrite",
        "--no-plots",
    ]
    completed = subprocess.run(
        cmd,
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return completed.stdout.strip()


def _rounded(
    draw: ImageDraw.ImageDraw,
    box: tuple[int, int, int, int],
    fill: str,
    outline: str | None = None,
) -> None:
    draw.rounded_rectangle(box, radius=8, fill=fill, outline=outline, width=1 if outline else 0)


def _text(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    value: str,
    font: ImageFont.ImageFont,
    fill: str = "#f8fafc",
) -> None:
    draw.text(xy, value, font=font, fill=fill)


def _terminal_lines(output: str) -> list[str]:
    lines = [
        "$ dicom-privacy-demo outputs/demo-media --no-plots",
        "Generated seeded synthetic DICOM benchmark",
        "Ran noop, metadata-only, and baseline controls",
        "Evaluated residual seeded identifiers",
        "Created review DB and publication package",
    ]
    try:
        payload = json.loads(output)
    except json.JSONDecodeError:
        return lines
    lines.append(f"Review cases: {payload['review_cases']}")
    lines.append(f"Manifest SHA256: {payload['demo_manifest_sha256'][:16]}...")
    return lines


def _draw_terminal(draw: ImageDraw.ImageDraw, output: str) -> None:
    _rounded(draw, (58, 176, 676, 640), "#08111f", "#20304b")
    y = 204
    for index, line in enumerate(_terminal_lines(output)):
        color = "#80cbc4" if index == 0 else "#d5dde8"
        _text(draw, (84, y), line, FONT_MONO, color)
        y += 34


def _pipeline_bar(
    draw: ImageDraw.ImageDraw,
    x: int,
    y: int,
    name: str,
    summary: dict[str, Any],
    color: str,
) -> None:
    removal = float(summary["removal_rate"])
    width = int(360 * removal)
    _text(draw, (x, y), name, FONT_SMALL, "#cbd5e1")
    _rounded(draw, (x, y + 30, x + 360, y + 56), "#1f2937")
    draw.rounded_rectangle((x, y + 30, x + width, y + 56), radius=8, fill=color)
    _text(draw, (x + 382, y + 30), f"{removal:.0%}", FONT_SMALL, "#f8fafc")
    _text(
        draw,
        (x, y + 66),
        f"removed {summary['removed_injections']} of {summary['injections']} seeded identifiers",
        FONT_SMALL,
        "#94a3b8",
    )


def _frame(summary: dict[str, Any], output: str, step: int) -> Image.Image:
    image = Image.new("RGB", (WIDTH, HEIGHT), "#0b1020")
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, WIDTH, 92), fill="#111827")
    _text(draw, (58, 26), "DICOM Privacy Auditor", FONT_TITLE)
    _text(draw, (58, 105), "Synthetic benchmark generated by the real CLI", FONT_H2, "#cbd5e1")
    _text(draw, (58, 144), "Generated DICOM objects only. Not a compliance certificate.", FONT_SMALL, "#94a3b8")

    _draw_terminal(draw, output)
    _rounded(draw, (716, 176, 1220, 640), "#101826", "#263244")
    _text(draw, (744, 206), "Residual removal by pipeline", FONT_H2)

    pipelines = [
        ("No-op control", "noop", "#f87171"),
        ("Metadata-only", "metadata-only", "#fbbf24"),
        ("Benchmark baseline", "baseline", "#34d399"),
    ]
    for index, (label, key, color) in enumerate(pipelines[: step + 1]):
        _pipeline_bar(draw, 744, 270 + index * 112, label, summary[key], color)

    if step >= 2:
        _text(draw, (744, 600), "Review DB and publication package included.", FONT_SMALL, "#a7b4c8")
    return image


def _write_media(frames: list[Image.Image]) -> None:
    import imageio.v2 as imageio
    import numpy as np

    ASSETS.mkdir(parents=True, exist_ok=True)
    poster = ASSETS / "demo-poster.png"
    gif = ASSETS / "demo.gif"
    mp4 = ASSETS / "demo.mp4"
    frames[-1].save(poster, optimize=True)
    imageio.mimsave(gif, frames, duration=1.2, loop=0)
    with imageio.get_writer(mp4, fps=1, codec="libx264", quality=8, macro_block_size=None) as writer:
        for frame in frames:
            writer.append_data(np.asarray(frame))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=WORKSPACE)
    args = parser.parse_args()

    output = _run_demo(args.workspace)
    summary = json.loads((args.workspace / "summary.json").read_text(encoding="utf-8"))
    frames = [_frame(summary, output, step) for step in range(3)]
    _write_media(frames)
    print(f"Wrote {ASSETS / 'demo-poster.png'}")
    print(f"Wrote {ASSETS / 'demo.gif'}")
    print(f"Wrote {ASSETS / 'demo.mp4'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
